name: Run the testsuite

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: '12'
            - run: npm cit
              env:
                  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
